version: '3.9'

services:
  users:
    container_name: users
    build:
      dockerfile: Dockerfile
    image: users:latest
    ports:
      - "8088:8080"
    networks:
      - users-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  users-network:
    driver: bridge
